# Generated by Django 5.0.1 on 2025-11-17 05:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "preferred_communication",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("phone", "Phone"),
                            ("none", "No Communication"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("email_opt_in", models.BooleanField(default=True)),
                ("sms_opt_in", models.BooleanField(default=False)),
                (
                    "donor_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("corporate", "Corporate"),
                            ("foundation", "Foundation"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(default="US", max_length=2)),
                (
                    "total_donated",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("donation_count", models.IntegerField(default=0)),
                ("first_donation_date", models.DateTimeField(blank=True, null=True)),
                ("last_donation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "average_donation",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("new", "New Donor"),
                            ("active", "Active"),
                            ("lapsed", "Lapsed"),
                            ("reactivated", "Reactivated"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "engagement_score",
                    models.IntegerField(
                        default=0, help_text="0-100 score based on giving patterns"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Manual tags like 'major donor', 'monthly'",
                    ),
                ),
                (
                    "source_channel",
                    models.CharField(
                        blank=True, help_text="web, event, referral, etc.", max_length=50
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_donation_date"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("mission_statement", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                (
                    "ein",
                    models.CharField(
                        blank=True, help_text="Employer Identification Number", max_length=20
                    ),
                ),
                ("tax_exempt_status", models.BooleanField(default=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="organization_logos/")),
                (
                    "primary_color",
                    models.CharField(default="#233D00", help_text="Hex color code", max_length=7),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending Approval"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("stripe_account_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_featured"], name="core_organi_status_71c14a_idx"
                    ),
                    models.Index(fields=["slug"], name="core_organi_slug_517c11_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("general", "General Fund"),
                            ("project", "Specific Project"),
                            ("emergency", "Emergency Relief"),
                            ("matching", "Matching Campaign"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("1.00"))],
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "amount_raised",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("donor_count", models.IntegerField(default=0)),
                ("is_matching", models.BooleanField(default=False)),
                (
                    "matching_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("matching_sponsor", models.CharField(blank=True, max_length=255)),
                (
                    "impact_metric_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'meals provided', 'families fed'",
                        max_length=100,
                    ),
                ),
                (
                    "impact_metric_value",
                    models.IntegerField(
                        blank=True, help_text="How many units per $X donated", null=True
                    ),
                ),
                (
                    "impact_metric_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dollar amount for impact metric (e.g., $25 = 1 family fed)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="campaign_images/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("live", "Live"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("1.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("stripe_subscription_id", models.CharField(max_length=255, unique=True)),
                ("stripe_customer_id", models.CharField(max_length=255)),
                ("stripe_price_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("total_payments", models.IntegerField(default=0)),
                ("successful_payments", models.IntegerField(default=0)),
                ("failed_payments", models.IntegerField(default=0)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("next_payment_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_donations",
                        to="core.campaign",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_donations",
                        to="core.donorprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_donations",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("1.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "donation_type",
                    models.CharField(
                        choices=[("one_time", "One-Time"), ("recurring", "Recurring")],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("covers_processing_fee", models.BooleanField(default=False)),
                (
                    "processing_fee_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("stripe_charge_id", models.CharField(blank=True, max_length=255)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                ("stripe_subscription_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "dedication_type",
                    models.CharField(
                        choices=[
                            ("in_honor", "In Honor Of"),
                            ("in_memory", "In Memory Of"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("dedication_name", models.CharField(blank=True, max_length=255)),
                ("donor_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="core.campaign",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations",
                        to="core.donorprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations",
                        to="core.organization",
                    ),
                ),
                (
                    "recurring_donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_history",
                        to="core.recurringdonation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("receipt_date", models.DateTimeField(auto_now_add=True)),
                ("tax_year", models.IntegerField()),
                ("donor_name", models.CharField(max_length=255)),
                ("donor_email", models.EmailField(max_length=254)),
                ("donor_address", models.TextField(blank=True)),
                ("organization_name", models.CharField(max_length=255)),
                ("organization_ein", models.CharField(blank=True, max_length=20)),
                ("organization_address", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="receipts/%Y/")),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="core.donation",
                    ),
                ),
            ],
            options={
                "ordering": ["-receipt_date"],
                "indexes": [
                    models.Index(fields=["receipt_number"], name="core_donati_receipt_e67584_idx"),
                    models.Index(
                        fields=["tax_year", "donor_email"], name="core_donati_tax_yea_a64228_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="donorprofile",
            index=models.Index(
                fields=["stripe_customer_id"], name="core_donorp_stripe__200e8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donorprofile",
            index=models.Index(
                fields=["lifecycle_status", "engagement_score"],
                name="core_donorp_lifecyc_12ae9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="donorprofile",
            index=models.Index(
                fields=["last_donation_date"], name="core_donorp_last_do_528b83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "is_featured"], name="core_campai_status_6143a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["organization", "status"], name="core_campai_organiz_41ba95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["slug"], name="core_campai_slug_6c73df_idx"),
        ),
        migrations.AddIndex(
            model_name="recurringdonation",
            index=models.Index(fields=["donor", "status"], name="core_recurr_donor_i_ff3907_idx"),
        ),
        migrations.AddIndex(
            model_name="recurringdonation",
            index=models.Index(
                fields=["stripe_subscription_id"], name="core_recurr_stripe__c45782_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringdonation",
            index=models.Index(
                fields=["status", "next_payment_date"], name="core_recurr_status_51abc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["donor", "status"], name="core_donati_donor_i_0294b7_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["organization", "status"], name="core_donati_organiz_7e229b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["campaign", "status"], name="core_donati_campaig_3e9810_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["stripe_payment_intent_id"], name="core_donati_stripe__105dcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["stripe_subscription_id"], name="core_donati_stripe__dad691_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["created_at"], name="core_donati_created_b3c808_idx"),
        ),
    ]
