# Generated by Django 5.0.1 on 2025-11-20 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")],
                        default="email",
                        max_length=10,
                    ),
                ),
                (
                    "roles",
                    models.JSONField(default=list, help_text="List of opportunity IDs or titles"),
                ),
                ("availability", models.TextField()),
                ("resume", models.FileField(blank=True, null=True, upload_to="volunteer_resumes/")),
                ("linkedin", models.URLField(blank=True)),
                ("accessibility_notes", models.TextField(blank=True)),
                ("transportation", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField(blank=True)),
                ("orientation_agreed", models.BooleanField(default=False)),
                ("photo_consent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("contacted", "Contacted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Internal notes from reviewers")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("emoji", models.CharField(default="📋", max_length=10)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("kitchen", "Kitchen"),
                            ("logistics", "Logistics"),
                            ("support", "Support"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(help_text="e.g., 'Mon-Fri (few hrs/day)'", max_length=100),
                ),
                (
                    "duties",
                    models.JSONField(default=list, help_text="List of duties/responsibilities"),
                ),
                ("ideal_for", models.TextField(help_text="Who this role is ideal for")),
                ("summary", models.TextField(help_text="Brief summary of the role")),
                (
                    "days_available",
                    models.JSONField(
                        default=list, help_text="List of day slugs: ['monday', 'tuesday']"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.RemoveIndex(
            model_name="donationreceipt",
            name="core_donati_receipt_e67584_idx",
        ),
        migrations.RemoveIndex(
            model_name="donationreceipt",
            name="core_donati_tax_yea_a64228_idx",
        ),
        migrations.RemoveField(
            model_name="donationreceipt",
            name="created_at",
        ),
        migrations.AddIndex(
            model_name="donationreceipt",
            index=models.Index(
                fields=["tax_year", "receipt_date"], name="core_donati_tax_yea_105e80_idx"
            ),
        ),
        migrations.AddField(
            model_name="organizationadmin",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_admins_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationadmin",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationadmin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_admin_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteeropportunity",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_opportunities_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organizationadmin",
            index=models.Index(
                fields=["user", "organization"], name="core_organi_user_id_302fdd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationadmin",
            unique_together={("user", "organization")},
        ),
        migrations.AddIndex(
            model_name="volunteerapplication",
            index=models.Index(
                fields=["status", "created_at"], name="core_volunt_status_adb4bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerapplication",
            index=models.Index(fields=["email"], name="core_volunt_email_351dae_idx"),
        ),
        migrations.AddIndex(
            model_name="volunteeropportunity",
            index=models.Index(
                fields=["category", "is_active"], name="core_volunt_categor_f3b407_idx"
            ),
        ),
    ]
