# Generated by Django 5.0.1 on 2025-11-20 06:04

from django.db import migrations


def create_volunteer_opportunities(apps, schema_editor):
    """Populate volunteer opportunities with original Seed & Spoon roles"""
    VolunteerOpportunity = apps.get_model('core', 'VolunteerOpportunity')
    
    opportunities = [
        {
            'title': 'Planners / Admins',
            'emoji': '\U0001F4CB',
            'slug': 'planners-admins',
            'category': 'admin',
            'schedule': 'Mon-Fri (few hrs/day)',
            'duties': ['Manage rosters and volunteer schedules', 'Handle donor communication and outreach', 'Maintain data systems and records', 'Coordinate weekly meal plans', 'Support program operations'],
            'ideal_for': 'Detail-oriented organizers who love systems',
            'summary': 'Keeps the mission running smoothly behind the scenes.',
            'days_available': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
            'is_paid': False,
            'sort_order': 1
        },
        {
            'title': 'Shoppers',
            'emoji': '\U0001F6D2',
            'slug': 'shoppers',
            'category': 'logistics',
            'schedule': 'Tues & Fri',
            'duties': ['Pick up food donations from partners', 'Purchase needed ingredients', 'Load and transport items safely', 'Unload at storage sites', 'Track inventory and receipts'],
            'ideal_for': 'Drivers with reliable vehicles',
            'summary': 'Brings the ingredients that start every meal.',
            'days_available': ['Tuesday', 'Friday'],
            'is_paid': False,
            'sort_order': 2
        },
        {
            'title': 'Preppers',
            'emoji': '\U0001F955',
            'slug': 'preppers',
            'category': 'kitchen',
            'schedule': 'Wed',
            'duties': ['Wash and sanitize produce', 'Chop and prep ingredients', 'Label and organize items', 'Set up cooking stations', 'Follow food safety protocols'],
            'ideal_for': 'Team players who enjoy prep work',
            'summary': 'Light teamwork that fuels Thursday cook day.',
            'days_available': ['Wednesday'],
            'is_paid': False,
            'sort_order': 3
        },
        {
            'title': 'Cooks',
            'emoji': '\U0001F468\u200D\U0001F373',
            'slug': 'cooks',
            'category': 'kitchen',
            'schedule': 'Thurs',
            'duties': ['Cook large-batch meals from recipes', 'Monitor food temperatures and quality', 'Portion meals into containers', 'Label with dates and contents', 'Maintain kitchen cleanliness'],
            'ideal_for': 'Anyone who loves cooking with purpose',
            'summary': 'The heart of Seed & Spoon - where food becomes care.',
            'days_available': ['Thursday'],
            'is_paid': False,
            'sort_order': 4
        },
        {
            'title': 'Drivers / Delivery Team',
            'emoji': '\U0001F69A',
            'slug': 'drivers-delivery-team',
            'category': 'logistics',
            'schedule': 'Fri',
            'duties': ['Load meal boxes into delivery vehicles', 'Follow delivery routes and schedules', 'Deliver boxes safely to families', 'Maintain friendly, professional contact', 'Report any delivery issues'],
            'ideal_for': 'Licensed drivers with clean records',
            'summary': 'The bridge between kitchen and doorstep.',
            'days_available': ['Friday'],
            'is_paid': False,
            'sort_order': 5
        },
        {
            'title': 'Cleaners / Sanitation Team',
            'emoji': '\U0001F9FC',
            'slug': 'cleaners-sanitation-team',
            'category': 'support',
            'schedule': 'Wed-Fri',
            'duties': ['Sanitize cooking areas and equipment', 'Monitor food safety temperatures', 'Manage cleaning supplies inventory', 'Follow health department standards', 'Support kitchen and storage cleanliness'],
            'ideal_for': 'Detail-focused individuals',
            'summary': 'The backbone of safety and hygiene.',
            'days_available': ['Wednesday', 'Thursday', 'Friday'],
            'is_paid': True,
            'sort_order': 6
        },
        {
            'title': 'Youth Trainees (Seed Track)',
            'emoji': '\U0001F331',
            'slug': 'youth-trainees-seed-track',
            'category': 'support',
            'schedule': 'Wed-Thurs',
            'duties': ['Learn regenerative farming techniques', 'Assist with food preparation', 'Practice kitchen safety skills', 'Participate in mentorship sessions', 'Build professional experience'],
            'ideal_for': 'Ages 16-24 seeking job skills and purpose',
            'summary': 'Future farmers gaining purpose and skill.',
            'days_available': ['Wednesday', 'Thursday'],
            'is_paid': False,
            'sort_order': 7
        },
        {
            'title': 'Intake & Care Desk Volunteers',
            'emoji': '\U0001F481',
            'slug': 'intake-care-desk-volunteers',
            'category': 'support',
            'schedule': 'Wed-Fri',
            'duties': ['Greet families warmly and professionally', 'Check registration and eligibility', 'Share community resource information', 'Maintain confidential records', 'Answer questions with compassion'],
            'ideal_for': 'Friendly, empathetic communicators',
            'summary': 'The first friendly face for every guest.',
            'days_available': ['Wednesday', 'Thursday', 'Friday'],
            'is_paid': False,
            'sort_order': 8
        },
        {
            'title': 'Volunteer Case Managers',
            'emoji': '\U0001F4F1',
            'slug': 'volunteer-case-managers',
            'category': 'support',
            'schedule': 'Flexible (monthly check-ins)',
            'duties': ['Assess needs of new clients', 'Review progress toward goals', 'Maintain regular contact with families', 'Connect clients to resources', 'Document case notes securely'],
            'ideal_for': 'Social work students or caring mentors',
            'summary': 'The lifeline between families and Seed & Spoon.',
            'days_available': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
            'is_paid': True,
            'sort_order': 9
        },
        {
            'title': 'Community Meals Crew',
            'emoji': '\U0001F37D\uFE0F',
            'slug': 'community-meals-crew',
            'category': 'support',
            'schedule': 'Sat (scheduled)',
            'duties': ['Set up dining spaces for events', 'Serve meals to community members', 'Connect and build relationships', 'Clean up after service', 'Help create joyful atmosphere'],
            'ideal_for': 'People-lovers and relationship-builders',
            'summary': 'Turns service into shared joy.',
            'days_available': ['Saturday'],
            'is_paid': False,
            'sort_order': 10
        },
        {
            'title': 'Content & Storytelling Helpers',
            'emoji': '\U0001F4F8',
            'slug': 'content-storytelling-helpers',
            'category': 'support',
            'schedule': 'Flexible',
            'duties': ['Capture photos during events (with consent)', 'Document success stories', 'Help with social media content', 'Interview volunteers and families', 'Share impact with the community'],
            'ideal_for': 'Photographers, writers, and creatives',
            'summary': 'Gives voice to the mission.',
            'days_available': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
            'is_paid': False,
            'sort_order': 11
        },
        {
            'title': 'Corporate / Group Volunteers',
            'emoji': '\U0001F465',
            'slug': 'corporate-group-volunteers',
            'category': 'support',
            'schedule': 'Tues-Sat (scheduled)',
            'duties': ['Participate in group packing events', 'Prepare meal kits as a team', 'Sort and organize donations', 'Build team spirit through service', 'Custom projects based on needs'],
            'ideal_for': 'Corporate teams and community groups',
            'summary': 'Turns teamwork into tangible impact.',
            'days_available': ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
            'is_paid': False,
            'sort_order': 12
        },
        {
            'title': 'Super Fundraiser',
            'emoji': '\U0001F4B0',
            'slug': 'super-fundraiser',
            'category': 'admin',
            'schedule': 'Flexible (4-8 hrs/week)',
            'duties': ['Write compelling donor emails and appeals', 'Negotiate surplus agreements with stores', 'Organize food and clothing drives', 'Build relationships with corporate sponsors', 'Track fundraising metrics and goals'],
            'ideal_for': 'Charismatic communicators and negotiators',
            'summary': 'Keeps the mission funded and flowing.',
            'days_available': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
            'is_paid': False,
            'sort_order': 13
        },
    ]
    
    for opp_data in opportunities:
        VolunteerOpportunity.objects.create(
            is_active=True,
            **opp_data
        )


def reverse_func(apps, schema_editor):
    """Remove seeded volunteer opportunities"""
    VolunteerOpportunity = apps.get_model('core', 'VolunteerOpportunity')
    VolunteerOpportunity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organizationadmin_volunteerapplication_and_more"),
    ]

    operations = [
        migrations.RunPython(create_volunteer_opportunities, reverse_func),
    ]
